var trainData = [["You do not get over excited stand in spite of very large calm and relaxed , like I miss","positive"],
["god willing we are seeing today","positive"],
["awesome","positive"],
["Congrats","positive"],
["cool","positive"],
["Thx","positive"],
["Flower talent",,"positive"],
["Good radio broadcasts kralpop","positive"],
["whatever still laughing","positive"],
["The first part of new year","positive"],
["fifa I could have played it","positive"],
["Super great","positive"],
["Was my father's car Click to these sessions, you said I would walk around","positive"],
["I 'm tired traveler you my beautiful black","positive"],
["Thank you , gentlemen , I was very happy Adilcan","positive"],
["Ahmadis my 8 years with road logistics was welcome my friend's baby son duh God","positive"],
["a nice man born today are born good","positive"],
["Thank you","positive"],
["to wake up to good news","positive"],
["Hello again and welcome ","positive"],
["trucker concert show from center","positive"],
["I greet you with affection in order to meet the good news Look after yourself","positive"],
["It happens when we established the structure of India'slargest digital female choir","positive"],
["our country is falling a lot to do to make comments to lurk just sad we also instagram","negative"],
["March 21 World Down Syndrome Awareness Day is not a genetic disease","negative"],
["I find it extremely insufficient to date no general solution required that all but the head of the authority","negative"],
["Australian Academy Award for best supporting actor Oscar died of millet not such a success that a congratulations Master","negative"],
["talk very happy here at 00:00 tonight then tomorrow 's a little late","negative"],
["I find it difficult even not in this house you head two civilized human beings","negative"],
["ok damaged morale","negative"],
["I want to cry","negative"],
["We are at home or bi whimpering little bit bad rue olsn GT you 're not exactly in the best sequence Billah valllahi","negative"],
["If the father of us who knew serenade or bi hi , my nerves broke aglica","negative"],
["I do not ever be played on this day","negative"],
["sorry","negative"],
["disgrace","negative"],
["I'm very bad morale","negative"],
["I can not sleep at night","negative"],
["how bad a person","negative"],
["I regret very glad to know you","negative"],
["We have lost more movies we grew up with a veteran player. Thanks to our own . Clever space be heaven Alasya","negative"],
["life is hard","negative"],
["Morale cut distorted sound","negative"],
["The weather was so hot I just cried . Honker Honker","negative"],
["a not so smelly socks","negative"],
["Everyone dies, is buried in the soil Some hearts Some","negative"],
["I'd say the patient from entering the sea in Istanbul, but even patients with runny noses sucker exam eve","negative"]]


module.exports = trainData;



